#' Create and analyze Optimal Channel Networks.
#'
#' A package that allows the generation and analysis of synthetic river network analogues, called Optimal Channel Networks (OCNs). 
#' 
#' Add details.
#' 
#' @author 
#' Luca Carraro (\email{luca.carraro@@hotmail.it}), Florian Altermatt, Emanuel A. Fronhofer, Isabelle Gounand, Andrea Rinaldo, Enrico Bertuzzo
#' 
#' @seealso \href{../doc/OCNet.html}{\code{vignette("OCNet")}}
#' 
#' @section References:
#' 
#' Rinaldo, A., Rigon, R., Banavar, J. R., Maritan, A., & Rodriguez-Iturbe, I. (2014). Evolution and selection of river networks: Statics, dynamics, and complexity. Proceedings of the National Academy of Sciences of the United States of America, 111(7), 2417-2424. doi:10.1073/pnas.1322700111
#' 
#' Carraro et al.
#' 
#' @aliases OCNetLocal
#' @name OCNet-package
#' @docType package
#' @import fields spam
#' @useDynLib OCNet, .registration = TRUE
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100)}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN1
#' @usage data(OCN1)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,type_initialstate = "T")}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN2
#' @usage data(OCN2)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,type_initialstate = "V")}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN3
#' @usage data(OCN3)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,N_outlet=2,OutletSide = c("S","N"),OutletPos = c(1,100),PeriodicBoundaries = "TRUE")}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN4
#' @usage data(OCN4)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,N_outlet="All")}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN5
#' @usage data(OCN5)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,CoolingRate = 1/(0.05*30*100*100))}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN6
#' @usage data(OCN6)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,CoolingRate = 1/(0.01*30*100*100))}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN7
#' @usage data(OCN7)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(200,200,OutletPos=1,type_initialstate = "V")}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN8
#' @usage data(OCN8)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,OutletPos = c(40,75,35,55),OutletSide = c("S","N","E","W"),N_outlet = 4)}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN9
#' @usage data(OCN9)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,OutletPos = c(40,75,35,55),OutletSide = c("S","N","E","W"),N_outlet = 4,PeriodicBoundaries = FALSE)}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN10
#' @usage data(OCN10)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(100,100,N_outlet = 2,OutletSide = c("N","S"),OutletPos = c(1,100),type_initialstate = "V",PeriodicBoundaries = "TRUE",CoolingRate = 1/(0.05*30*100*100))}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN11
#' @usage data(OCN11)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of OCN 
#'
#' An OCN generated by \code{create_OCN(200,100,N_outlet = 4,OutletSide = c("N","S","N","S"),OutletPos = c(1,150,150,1),type_initialstate = "V",PeriodicBoundaries = "TRUE",CoolingRate = 1/(0.05*30*100*100))}.
#'
#' @docType data
#' @keywords datasets
#' @name OCN12
#' @usage data(OCN12)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of large OCN 
#'
#' An OCN generated by \code{create_OCN(400, 400), PeriodicBoundaries = FALSE, type_initialstate = "T"}.
#'
#' @docType data
#' @keywords datasets
#' @name OCNlarge
#' @usage data(OCNlarge)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL

#' Example of small network 
#'
#' A network built on a 4x4 lattice for illustrative purposes.
#'
#' @docType data
#' @keywords datasets
#' @name example_4x4
#' @usage data(example_4x4)
#' @format A list. See \code{\link{create_OCN}} documentation for details.
NULL