# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NN_OCN <- function(dimX, dimY, periodicBoundaries, movement) {
    .Call(`_OCNet_NN_OCN`, dimX, dimY, periodicBoundaries, movement)
}

NN_river <- function(dimX, dimY, periodicBoundaries, movement, toDEM, nNodes) {
    .Call(`_OCNet_NN_river`, dimX, dimY, periodicBoundaries, movement, toDEM, nNodes)
}

NN_FD <- function(nNodes, dimX, dimY, NeighbouringNodes, toDEM) {
    .Call(`_OCNet_NN_FD`, nNodes, dimX, dimY, NeighbouringNodes, toDEM)
}

WSC <- function(nNodes, SC_to_FD, FD_to_SC, NeighbouringNodes) {
    .Call(`_OCNet_WSC`, nNodes, SC_to_FD, FD_to_SC, NeighbouringNodes)
}

continue_FD_SC <- function(IndexHeadpixel, FD_to_SC, SC_to_FD, downNode) {
    .Call(`_OCNet_continue_FD_SC`, IndexHeadpixel, FD_to_SC, SC_to_FD, downNode)
}

paths_cpp <- function(OCN, whichNodes, str = "RN", includePaths = FALSE, includeDownstreamNode = FALSE, includeUnconnectedPaths = FALSE) {
    .Call(`_OCNet_paths_cpp`, OCN, whichNodes, str, includePaths, includeDownstreamNode, includeUnconnectedPaths)
}

