# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WSC <- function(nNodes, SC_to_FD, FD_to_SC, NeighbouringNodes) {
    .Call(`_OCNet_WSC`, nNodes, SC_to_FD, FD_to_SC, NeighbouringNodes)
}

paths_cpp <- function(OCN, str = "RN", includePaths = FALSE, includeDownstreamNode = FALSE, includeUnconnectedPaths = FALSE) {
    .Call(`_OCNet_paths_cpp`, OCN, str, includePaths, includeDownstreamNode, includeUnconnectedPaths)
}

