# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NN_OCN <- function(dimX, dimY, periodicBoundaries, movement) {
    .Call(`_OCNet_NN_OCN`, dimX, dimY, periodicBoundaries, movement)
}

NN_river <- function(dimX, dimY, periodicBoundaries, movement, toDEM, nNodes) {
    .Call(`_OCNet_NN_river`, dimX, dimY, periodicBoundaries, movement, toDEM, nNodes)
}

WSC <- function(nNodes, SC_to_FD, FD_to_SC, NeighbouringNodes) {
    .Call(`_OCNet_WSC`, nNodes, SC_to_FD, FD_to_SC, NeighbouringNodes)
}

paths_cpp <- function(OCN, str = "RN", includePaths = FALSE, includeDownstreamNode = FALSE, includeUnconnectedPaths = FALSE) {
    .Call(`_OCNet_paths_cpp`, OCN, str, includePaths, includeDownstreamNode, includeUnconnectedPaths)
}

